[package]
name = "learn-rust"
version = "0.1.0"
edition = "2018" # rust版本

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

# 依赖
[dependencies]



# rust 中,第三方包叫做crate